version: "3.7"
services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_LOG_STATEMENT: "all"
      POSTGRES_LOG_MIN_MESSAGES: "debug1"
    ports:
      - "5433:5432"

volumes:
  db_data:
